//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class oldWF_BillFlowNodeRemark
    {
        public int BillFlowNodeRemarkID { get; set; }
        public Nullable<int> BillFlowNodeID { get; set; }
        public Nullable<int> TransactorID { get; set; }
        public string Transactor { get; set; }
        public Nullable<System.DateTime> TransactorDate { get; set; }
        public string TransactorOperation { get; set; }
        public string TransactorRemark { get; set; }
    
        public virtual oldWF_BillFlowNode oldWF_BillFlowNode { get; set; }
    }
}
