//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class oldWF_BillFlowNode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public oldWF_BillFlowNode()
        {
            this.oldWF_BillFlowNodeRemark = new HashSet<oldWF_BillFlowNodeRemark>();
        }
    
        public int BillFlowNodeID { get; set; }
        public Nullable<int> WorkFlowNodeID { get; set; }
        public Nullable<int> NodeStateID { get; set; }
        public Nullable<int> WorkFlowID { get; set; }
        public Nullable<int> BillID { get; set; }
    
        public virtual oldWF_WorkFlowNode oldWF_WorkFlowNode { get; set; }
        public virtual oldWF_NodeState oldWF_NodeState { get; set; }
        public virtual oldWF_WorkFlow oldWF_WorkFlow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oldWF_BillFlowNodeRemark> oldWF_BillFlowNodeRemark { get; set; }
    }
}
