//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class oldWF_WorkFlowNode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public oldWF_WorkFlowNode()
        {
            this.oldWF_AutoTransactNode = new HashSet<oldWF_AutoTransactNode>();
            this.oldWF_BillFlowNode = new HashSet<oldWF_BillFlowNode>();
        }
    
        public int WorkFlowNodeID { get; set; }
        public Nullable<int> WorkFlowID { get; set; }
        public Nullable<int> NodeID { get; set; }
        public Nullable<int> WorkFlowNodeSequence { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oldWF_AutoTransactNode> oldWF_AutoTransactNode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oldWF_BillFlowNode> oldWF_BillFlowNode { get; set; }
        public virtual oldWF_Node oldWF_Node { get; set; }
        public virtual oldWF_WorkFlow oldWF_WorkFlow { get; set; }
    }
}
