//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_WorkFlow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public W_WorkFlow()
        {
            this.W_WorkFlowNode = new HashSet<W_WorkFlowNode>();
        }
    
        public int wf_Id { get; set; }
        public string wf_Name { get; set; }
        public string wf_Remark { get; set; }
        public bool wf_IsDel { get; set; }
        public System.DateTime wf_Addtime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<W_WorkFlowNode> W_WorkFlowNode { get; set; }
    }
}
