//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class W_WrokFlowRole
    {
        public int wfr_Id { get; set; }
        public int wfr_WFNode { get; set; }
        public int wfr_Role { get; set; }
    
        public virtual Ou_Role Ou_Role { get; set; }
        public virtual W_WorkFlowNode W_WorkFlowNode { get; set; }
    }
}
