//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WR_WorkFlowApply
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WR_WorkFlowApply()
        {
            this.WR_WrokFlowApplyDetails = new HashSet<WR_WrokFlowApplyDetails>();
        }
    
        public int wr_Id { get; set; }
        public int wr_UserId { get; set; }
        public int wr_WFId { get; set; }
        public int wf_CurWFNId { get; set; }
        public string wf_Title { get; set; }
        public string wf_Content { get; set; }
        public int wf_State { get; set; }
        public Nullable<int> wf_TargetUserId { get; set; }
        public int wf_Priority { get; set; }
        public System.DateTime wf_Addtime { get; set; }
        public bool wf_IsDel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WR_WrokFlowApplyDetails> WR_WrokFlowApplyDetails { get; set; }
    }
}
